version: '3.8'
services:

  service_business:
    build:
      context: .
      dockerfile: Services/Business/Dockerfile
    container_name: "container_business"
    ports:     
      - "5000:5000"
      - "8077:8077"
      - ":5672"
      - "5432:5432"
    # volumes:
    #   - ./config:/root/config

  # rabbitmq:
  #   container_name: "rabbitmq"
  #   image: rabbitmq:management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  # postgres:
  #   image: postgres:latest
  #   container_name: "scsmarketplace-postgres"
  #   environment:
  #     POSTGRES_DB: marketplace-1
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: prosperas_password
  #   ports:
  #     - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: "pgadmin"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadminpassword
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres
