// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Persistence;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231002121205_InitMigrationTest")]
    partial class InitMigrationTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.Account.AccountModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTimeOffset>("collectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("consumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("denied")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("depositAcct")
                        .HasColumnType("text");

                    b.Property<long>("listingId")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<long>("productId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
